import LoginPage from './loginPage';
import RegisterPage from './registerUser';
import PSignupPage from './providerSignupPage';
import UserResultPage from './userResultPage';
import UserSignupPage from './signupPage';
import UserInfo from './userInfo';
import UserPayment from './userPayment';
import UserLandingPage from './userLandingPage';
import UserHistory from './userHistory';
import ProviderHistory from './providerHistory';
import ProviderIncomingAppointment from './providerIncomingAppointment'